version: '3.9'

services:
  99ai:
    image: ccr.ccs.tencentyun.com/ibfpig/pockyt:0.0.3
    container_name: 99ai
    restart: always
    ports:
      - "9520:9520"
    volumes:
      - ./.env:/app/.env:rw
    env_file:
      - ./.env
    environment:
      - TZ=Asia/Shanghai
